/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.DangNhapDAO;
import DAO.NhanVienDAO;
import DAO.SQLServerProvider;
import POJO.NhanVien;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author tranc
 */
public class DangNhap extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    public DangNhap() {

        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbUs = new javax.swing.JLabel();
        jLabelPW = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        errLogin = new javax.swing.JLabel();
        btnreset = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jlbForgotPW = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtPassWord = new javax.swing.JPasswordField();
        Bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbUs.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbUs.setForeground(new java.awt.Color(255, 255, 255));
        jlbUs.setText("Username :");
        getContentPane().add(jlbUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 100, 30));

        jLabelPW.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelPW.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPW.setText("Password : ");
        getContentPane().add(jLabelPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 100, 30));

        txtUsername.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 200, 30));

        btnExit.setBackground(new java.awt.Color(153, 153, 255));
        btnExit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, -1));

        title.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 255, 255));
        title.setText("Đăng Nhập");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 130, -1));

        errLogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        errLogin.setForeground(new java.awt.Color(204, 0, 51));
        getContentPane().add(errLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 310, -1));

        btnreset.setBackground(new java.awt.Color(153, 153, 255));
        btnreset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnreset.setForeground(new java.awt.Color(255, 255, 255));
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        getContentPane().add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        btnLogin.setBackground(new java.awt.Color(153, 153, 255));
        btnLogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        jlbForgotPW.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbForgotPW.setForeground(new java.awt.Color(51, 51, 255));
        jlbForgotPW.setText("You forgot your password ?");
        jlbForgotPW.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 204)));
        getContentPane().add(jlbForgotPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 190, -1));

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/yees.png"))); // NOI18N
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 30, 30));

        txtPassWord.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        getContentPane().add(txtPassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 200, 30));

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/login.jpg"))); // NOI18N
        getContentPane().add(Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int chose = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Thoát?", "Thông Báo", JOptionPane.YES_NO_OPTION);
        if (chose == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        txtPassWord.setText("");
        txtUsername.setText("");
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String user, pass;
        user = txtUsername.getText();
        pass = txtPassWord.getText();
        if (user.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin đăng nhập!");
        } else {
            SQLServerProvider provider = new SQLServerProvider();
            if (provider.checkConnection(user, pass)) {
                DangNhapDAO dn = new DangNhapDAO();
                String id = dn.getIdEmployeesByUsername(user);
                if (!id.isEmpty()) {
                    NhanVienDAO nv = new NhanVienDAO();
                    NhanVien emp = emp = nv.getInformationEmployeebyID(id);
                    if (emp != null) {
                        String role;
                        try {
                             role = provider.getUserRole(user); // Gọi hàm hoặc stored procedure để lấy vai trò của người dùng
                             if (role.equals("Manager")) {
                                JOptionPane.showMessageDialog(rootPane, "Đăng nhập thành công với vai trò Manager");
                                Main f = new Main(emp);
                                f.setVisible(true);
                                setVisible(false);
                             } 
                             else if (role.equals("Staff")) {
                                JOptionPane.showMessageDialog(rootPane, "Đăng nhập thành công với vai trò Staff");
                                Main f = new Main(emp);
                                f.setVisible(true);
                                setVisible(false);
                                
                                this.dispose();
                         } 
                         } catch (SQLException ex) {
                             Logger.getLogger(DangNhap.class.getName()).log(Level.SEVERE, null, ex);
                         }
                     
                    }
                }
                 
             
                // Xử lý dựa trên vai trò của người dùng
                
            } else {
                JOptionPane.showMessageDialog(this, "Đăng Nhập thất bại!");
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (txtPassWord.getEchoChar() == 0) {
            txtPassWord.setEchoChar('\u2022');
        } else {
            txtPassWord.setEchoChar((char) 0);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bg;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnreset;
    private javax.swing.JLabel errLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelPW;
    private javax.swing.JLabel jlbForgotPW;
    private javax.swing.JLabel jlbUs;
    private javax.swing.JLabel title;
    private javax.swing.JPasswordField txtPassWord;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
