/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import DAO.SupplierDAO;
import POJO.Supplier;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author tranc
 */
public class jfrmSuplier extends javax.swing.JInternalFrame {

    /**
     * Creates new form jfrmSuplier
     */
    DefaultTableModel dtm = new DefaultTableModel();
    public jfrmSuplier() {
        initComponents();
        txt_idNCC.setEnabled(false);
        txt_idNCC.setEditable(false); 
        LoadForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_idNCC = new javax.swing.JLabel();
        lbl_tenNCC = new javax.swing.JLabel();
        lbl_sdtNCC = new javax.swing.JLabel();
        lbl_dcNCC = new javax.swing.JLabel();
        lbl_emailNCC = new javax.swing.JLabel();
        txt_idNCC = new javax.swing.JTextField();
        txt_tenNCC = new javax.swing.JTextField();
        txt_sdtNCC = new javax.swing.JTextField();
        txt_dcNCC = new javax.swing.JTextField();
        txt_EmailNCC = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txt_Timkiem = new javax.swing.JTextField();
        btnDong = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnDatLai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ListTT = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1344, 729));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SUPPLIER", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nhà cung cấp", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        lbl_idNCC.setText("ID");

        lbl_tenNCC.setText("Name");

        lbl_sdtNCC.setText("Phone");

        lbl_dcNCC.setText("Address");

        lbl_emailNCC.setText("Email");

        txt_sdtNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sdtNCCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_idNCC)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_dcNCC)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_tenNCC)
                                .addComponent(lbl_sdtNCC))
                            .addComponent(lbl_emailNCC))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_idNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_sdtNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_dcNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_EmailNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_idNCC)
                    .addComponent(txt_idNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tenNCC))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_sdtNCC)
                    .addComponent(txt_sdtNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_dcNCC)
                    .addComponent(txt_dcNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_emailNCC)
                    .addComponent(txt_EmailNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txt_Timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDong)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDong)
                    .addComponent(btnTimKiem))
                .addGap(21, 21, 21))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thực hiện thao tác", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnDatLai.setText("Đặt lại");
        btnDatLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnThem)
                .addGap(63, 63, 63)
                .addComponent(btnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSua)
                .addGap(45, 45, 45)
                .addComponent(btnDatLai)
                .addGap(23, 23, 23))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnDatLai))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        tbl_ListTT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_ListTT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ListTTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_ListTT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_sdtNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sdtNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sdtNCCActionPerformed

    private void tbl_ListTTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ListTTMouseClicked
    
                int row = tbl_ListTT.getSelectedRow();
                // Kiểm tra xem có hàng nào được chọn không
                if (row >= 0 && row < tbl_ListTT.getRowCount()) {
                    String idNCC = tbl_ListTT.getValueAt(row, 0).toString();
                    String tenNCC = tbl_ListTT.getValueAt(row, 1).toString();
                    String sdtNCC = tbl_ListTT.getValueAt(row, 2).toString();
                    String dcNCC = tbl_ListTT.getValueAt(row, 3).toString();
                    String emailNCC = tbl_ListTT.getValueAt(row, 4).toString();
                    // Hiển thị dữ liệu lên các trường tương ứng
                    txt_idNCC.setText(idNCC);
                    txt_tenNCC.setText(tenNCC);
                    txt_sdtNCC.setText(sdtNCC);
                    txt_dcNCC.setText(dcNCC);
                    txt_EmailNCC.setText(emailNCC);
                } 
    }//GEN-LAST:event_tbl_ListTTMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        SupplierDAO supplierDAO = new SupplierDAO();
        String tenNCC = txt_tenNCC.getText().trim();
        String sdtNCC = txt_sdtNCC.getText().trim();
        String dcNCC = txt_dcNCC.getText().trim();
        String emailNCC = txt_EmailNCC.getText().trim();

        if (tenNCC.isEmpty() || sdtNCC.isEmpty() || dcNCC.isEmpty() || emailNCC.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin nhà cung cấp!");
            return;
        }

            boolean themThanhCong = supplierDAO.themNhaCungCap(tenNCC, sdtNCC, dcNCC, emailNCC);

            // Kiểm tra kết quả và xử lý tương ứng
            if (themThanhCong) {
                txt_idNCC.setText(" ");
                txt_tenNCC.setText("");
                txt_sdtNCC.setText("");
                txt_dcNCC.setText("");
                txt_EmailNCC.setText("");
                LoadForm();
                JOptionPane.showMessageDialog(this, "Thêm nhà cung cấp thành công!");
            } else {
                JOptionPane.showMessageDialog(this, "Thêm nhà cung cấp thất bại!");
            }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
         String idNCC = txt_idNCC.getText().trim();

    if (idNCC.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn nhà cung cấp để xóa!");
        return;
    }

    // Hiển thị hộp thoại xác nhận YES/NO
    int choice = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa nhà cung cấp này?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
    if (choice == JOptionPane.YES_OPTION) {
        boolean xoaThanhCong = SupplierDAO.xoaNhaCungCap(idNCC);
        if (xoaThanhCong) {
            JOptionPane.showMessageDialog(this, "Xóa nhà cung cấp thành công!");
            LoadForm();
            txt_idNCC.setText(" ");
            txt_tenNCC.setText(" ");
            txt_sdtNCC.setText(" ");
            txt_dcNCC.setText(" ");
            txt_EmailNCC.setText(" ");
        } else {
            JOptionPane.showMessageDialog(this, "Xóa nhà cung cấp thất bại!");
        }
    } else {
        // Hiển thị thông báo hủy xóa
        JOptionPane.showMessageDialog(this, "Hủy xóa nhà cung cấp.");
    }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnDatLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatLaiActionPerformed
        txt_idNCC.setText(" ");
        txt_tenNCC.setText(" ");
        txt_sdtNCC.setText(" ");
        txt_dcNCC.setText(" ");
        txt_EmailNCC.setText(" ");
        txt_Timkiem.setText(" ");
        DefaultTableModel model = (DefaultTableModel) tbl_ListTT.getModel();
        model.setRowCount(0); 
        LoadForm();
    }//GEN-LAST:event_btnDatLaiActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String searchText = txt_Timkiem.getText().trim();

        // Kiểm tra xem chuỗi tìm kiếm có rỗng không
        if (searchText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập từ khóa tìm kiếm!");
            return;
        }
        List<Supplier> suppliers = SupplierDAO.timKiemNhaCungCap(searchText);

        // Hiển thị kết quả tìm kiếm trên bảng
        DefaultTableModel model = (DefaultTableModel) tbl_ListTT.getModel();
        model.setRowCount(0);
        for (Supplier supplier : suppliers) {
            model.addRow(new Object[]{
                supplier.getIdSupplier(),
                supplier.getName(),
                supplier.getPhone(),
                supplier.getAddress(),
                supplier.getEmail()
            });
        }                 
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        txt_Timkiem.setText(""); 
        DefaultTableModel model = (DefaultTableModel) tbl_ListTT.getModel();
        model.setRowCount(0);
        LoadForm();
    }//GEN-LAST:event_btnDongActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        String idNCC = txt_idNCC.getText();
        String tenNCC = txt_tenNCC.getText();
        String sdtNCC = txt_sdtNCC.getText();
        String dcNCC = txt_dcNCC.getText();
        String emailNCC = txt_EmailNCC.getText();

        boolean capNhatThanhCong = SupplierDAO.capNhatNhaCungCap(idNCC, tenNCC, sdtNCC, dcNCC, emailNCC);
    
        if (capNhatThanhCong) {
            DefaultTableModel model = (DefaultTableModel) tbl_ListTT.getModel();
            int selectedRowIndex = tbl_ListTT.getSelectedRow();
            if (selectedRowIndex != -1) {
                model.setValueAt(tenNCC, selectedRowIndex, 1);
                model.setValueAt(sdtNCC, selectedRowIndex, 2);
                model.setValueAt(dcNCC, selectedRowIndex, 3);
                model.setValueAt(emailNCC, selectedRowIndex, 4);
            }
            JOptionPane.showMessageDialog(this, "Cập nhật thông tin nhà cung cấp thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật thông tin nhà cung cấp thất bại!");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    
    public void LoadForm() {
        SupplierDAO supplierDAO = new SupplierDAO();
        ArrayList<Supplier> dsNCC = SupplierDAO.layDanhsachNCC(); // Gọi phương thức trên đối tượng, không phải trực tiếp từ lớp
        DefaultTableModel defaultTableModel = (DefaultTableModel) tbl_ListTT.getModel();
        defaultTableModel.setColumnCount(0);
        defaultTableModel.setRowCount(0);
        // Đã đổi tên biến để phù hợp với việc khởi tạo
        defaultTableModel.addColumn("ID Nhà Cung Cấp");
        defaultTableModel.addColumn("Tên Nhà Cung Cấp");
        defaultTableModel.addColumn("Số Điện thoại");
        defaultTableModel.addColumn("Địa chỉ");
        defaultTableModel.addColumn("Email");
        for (Supplier spr : dsNCC) {
            Vector<Object> vec = new Vector<>(); // Chỉ định tham số kiểu của Vector là Object
            vec.add(spr.getIdSupplier());
            vec.add(spr.getName());
            vec.add(spr.getPhone());
            vec.add(spr.getAddress()); 
            vec.add(spr.getEmail());
            defaultTableModel.addRow(vec);
        }
        TableColumnModel columnModel = tbl_ListTT.getColumnModel();
        columnModel.getColumn(1).setPreferredWidth(150); // Độ rộng cho cột "Tên Nhà Cung Cấp"
        columnModel.getColumn(2).setPreferredWidth(150);  // Độ rộng cho cột "Số Điện thoại"
        columnModel.getColumn(4).setPreferredWidth(100); // Độ rộng cho cột "Email"
        JTableHeader header = tbl_ListTT.getTableHeader();
        header.setFont(new Font("Arial", Font.BOLD, 16)); // Font Arial, đậm, kích cỡ 16
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatLai;
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_dcNCC;
    private javax.swing.JLabel lbl_emailNCC;
    private javax.swing.JLabel lbl_idNCC;
    private javax.swing.JLabel lbl_sdtNCC;
    private javax.swing.JLabel lbl_tenNCC;
    private javax.swing.JTable tbl_ListTT;
    private javax.swing.JTextField txt_EmailNCC;
    private javax.swing.JTextField txt_Timkiem;
    private javax.swing.JTextField txt_dcNCC;
    private javax.swing.JTextField txt_idNCC;
    private javax.swing.JTextField txt_sdtNCC;
    private javax.swing.JTextField txt_tenNCC;
    // End of variables declaration//GEN-END:variables
}
