/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.SQLServerProvider;
import javax.swing.JOptionPane;

/**
 *
 * @author tranc
 */
public class ResetPassword extends javax.swing.JFrame {

    /**
     * Creates new form ResetPassword
     */
    public ResetPassword() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        erroNewResetPW = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        erroPassResetPW = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtPassWord = new javax.swing.JPasswordField();
        txtPassWordnew1 = new javax.swing.JPasswordField();
        txtPassWordnewComfirm = new javax.swing.JPasswordField();
        jBGResetPassW = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 90, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Confirm password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 160, 30));

        txtUsername.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 230, 30));

        btnBack.setBackground(new java.awt.Color(153, 153, 255));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Reset Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 180, -1));

        erroNewResetPW.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        erroNewResetPW.setForeground(new java.awt.Color(204, 0, 51));
        getContentPane().add(erroNewResetPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 270, -1));

        btnReset.setBackground(new java.awt.Color(153, 153, 255));
        btnReset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/yees.png"))); // NOI18N
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 30, 29));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("New Password :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 150, -1));

        jButton2.setBackground(new java.awt.Color(0, 51, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/yees.png"))); // NOI18N
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 30, 29));

        erroPassResetPW.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        erroPassResetPW.setForeground(new java.awt.Color(204, 0, 51));
        getContentPane().add(erroPassResetPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 280, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 90, -1));

        jButton3.setBackground(new java.awt.Color(0, 51, 153));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/yees.png"))); // NOI18N
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 30, 30));
        getContentPane().add(txtPassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 200, 30));
        getContentPane().add(txtPassWordnew1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 200, 30));
        getContentPane().add(txtPassWordnewComfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 200, 30));

        jBGResetPassW.setBackground(new java.awt.Color(204, 204, 255));
        jBGResetPassW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/login.jpg"))); // NOI18N
        getContentPane().add(jBGResetPassW, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
         
        String usersName = txtUsername.getText();
        String passWord = txtPassWord.getText();
        String confirmPass = txtPassWordnewComfirm.getText();
        String newPassWord = txtPassWordnew1.getText();
        if(usersName.isEmpty()||passWord.isEmpty()||confirmPass.isEmpty()||newPassWord.isEmpty()){
            erroNewResetPW.setText("Vui lòng nhập đầy đủ thông tin");
            erroPassResetPW.setText("");
        }
        else{
             SQLServerProvider provider = new SQLServerProvider();
             if(provider.checkConnection(usersName, passWord)){
                 if(confirmPass.equals(newPassWord)){
                     resetForm();
                    provider.open();
                     String sql = "EXEC sp_password @new = '"+newPassWord+"', @loginame = '"+usersName+"'";
                     System.out.println("Câu lệnh SQL: " + sql);
                     try {
                            int n = provider.executeUpdate(sql);            
                            JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công!");
                     } catch (Exception e) {
                         JOptionPane.showMessageDialog(null, "Đổi mật khẩu thất bại!");
                         e.printStackTrace();
                     } finally {
                       provider.close();
                     }
                    
                 }
                 else{
                     erroNewResetPW.setText("Mật khẩu không trùng khớp!");
                     erroPassResetPW.setText("");
                 }
             }
             else{
                 erroNewResetPW.setText("");
                 erroPassResetPW.setText("Tên đăng nhập hoặc mật khẩu không đúng?");
             }
        }
       
    }//GEN-LAST:event_btnResetActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if (txtPassWord.getEchoChar() == 0) {
            txtPassWord.setEchoChar('\u2022'); // Unicode của dấu *
        } else {
            txtPassWord.setEchoChar((char) 0); 
    }                              
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (txtPassWordnew1.getEchoChar() == 0) {
            txtPassWordnew1.setEchoChar('\u2022'); // Unicode của dấu *
        } else {
            txtPassWordnew1.setEchoChar((char) 0); 
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (txtPassWordnewComfirm.getEchoChar() == 0) {
            txtPassWordnewComfirm.setEchoChar('\u2022'); // Unicode của dấu *
        } else {
            txtPassWordnewComfirm.setEchoChar((char) 0); 
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel erroNewResetPW;
    private javax.swing.JLabel erroPassResetPW;
    private javax.swing.JLabel jBGResetPassW;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField txtPassWord;
    private javax.swing.JPasswordField txtPassWordnew1;
    private javax.swing.JPasswordField txtPassWordnewComfirm;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
private void resetForm(){
                     erroNewResetPW.setText("");
                     erroPassResetPW.setText("");
                     txtPassWord.setText("");
                     txtPassWordnew1.setText("");
                     txtUsername.setText("");
                     txtPassWordnewComfirm.setText("");
}
}

